---
name: Apply Prisma Migrations

on:
  workflow_dispatch:
    environment:
      type: choice
      description: 'Choose the environment'
      required: true
      options:
        - staging
        - production
    inputs:
      service:
        type: choice
        description: 'choose the service'
        required: true
        options:
          - clip-engine-api

jobs:
  apply-prisma:
    if: github.event.inputs.service == 'clip-engine-api'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get revert commit id
        run: |
          REVERT_COMMIT=$(git log -2 --pretty=format:"%H" | tail -n 1)
          echo "REVERT_COMMIT $REVERT_COMMIT"

      - name: Apply Prisma Migrations
        run: |
          cd /app/apps/clip-api
          pwd
          # dotenv -e ./config/.env.production
