name: Apply Prisma Migrations

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: "choose the service"
        required: true
        options:
          - clip-engine-api

jobs:
  apply-prisma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get recent commits
        id: recent_commits
        run: |
          git log -3 --pretty=format:"%H"
